### ISSUE TITLE
 Question about squiggle algorithms

### ISSUE THREAD

**Issue by JeremyQuo** [hiruna72/squigualiser#16]
I've noticed an interesting issue while observing the current.
Previously, the dwell time in the Tombo resquiggle method for nanopore sequencing was an uncertain value. However, in the new BAM file ‘mv’ tag and in your figure, it appears to take the format of n multiplied by a unit length.

    1.  I want to know why it changed and which will be better.
    2. Is the algorithm for Squiggle still the same as Tombo introduced?
    3. It seems in some cases in your example. still need to run f5c resquiggle. I wanna know when I need to run it. Will guppy or dorado return the squiggled data directly?

Thank you very much for your response.

**Comment by hiruna72** [comment]
Hi @JeremyQuo,

There are different ways you can approach the read to signal alignment.

1. I am not familiar with tombo. I once tried installing tombo and gave up. I think it is not even supporting latest fast5 files. You can get a crude alignment using the move table that is in the basecalled bam file.
2. F5c resquiggle should be different from tombo. Squigualiser does not support tombo output yet. Supporting tombo output on squigualiser is on the todo list. Not a priority though. Once it is supported, you can visualise different alignments. But I suggest you to use move table and f5c resquiggle alignment plots to compare for the moment. You can also simulate and plot the read you are interested in using squigualator and add it to the comparison.
3. F5c resquiggle is a more fine alignment than the move table in most cases. As you have noted, move table's alignment boundaries are always a multiple of the stride. This is not the case with f5c resquiggle.
