### ISSUE TITLE
About the move table information

### ISSUE THREAD

**Issue by Flower9618** [hiruna72/squigualiser#2]
Hi, I am interested in the move table information for nanopore. 
You said the number of 1 in the move table is the sequence length. However, I find for some read is right, but for others, the number of 1 is not same as the length of sequence. 
And for the move table and signal, I find the move table * stride not equal to the length of signal.
I do not know whether you meet this situation. 
Thank you very much.

**Comment by hiruna72** [comment]
Hi @Flower9618,
I think for the first question [this](https://github.com/nanoporetech/dorado/issues/110#issuecomment-1488882746) is a valid reason as you have figured out.

For the second, consider if the stride is 5 and signal length is 21 and the move array to be 1010. In that case 4 (move array length) * 5 (stride) = 20. Yes there will be a difference of less than the stride in most real  signals.

**Comment by hiruna72** [comment]
Hi @Flower9618,

Please feel free to reopen this issue if there is more to discuss.
