### ISSUE TITLE
Setup script exited with error: SandboxViolation

### ISSUE THREAD

**Issue by Grant-Fox** [hiruna72/squigualiser#25]
Hi squigualiser team! 

I encountered an error while trying to run the squigualiser program.
Commands ran: 
git clone https://github.com/hiruna72/squigualiser.git
cd squigualiser
python3 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools wheel
export PYSLOW5_ZSTD=1 
python setup.py install

The specific error message is as follows:
error: Setup script exited with error: SandboxViolation: mkdir('/PATH/TO/DIRECTORY/easy_install-qfz8h6wq/pysam-0.21.0/build', 511) {}

It seems that the package setup script is attempting to modify files outside the EasyInstall build area, resulting in an aborted installation. EasyInstall is unable to safely install the package, and there may be limitations in supporting alternative installation locations even if the setup script is executed manually.

Could there be some provided guidance or assistance regarding this problem? Any suggestions for a possible fix or workaround would be greatly appreciated.

Thank you for your attention to this matter.

Grant

**Comment by hiruna72** [comment]
Hello @Grant-Fox,

Which python version are you using? Recommended version is 3.8 or higher.
Can you please try the latest dev branch?
`git clone --branch dev https://github.com/hiruna72/squigualiser.git`

**Comment by Psy-Fer** [comment]
Hey,

Just to chime in.

When you have your environment active, what does it show when you run `which python`

If it's the python3 link In the environment, then all good. Just noticed the setup.py install command being run with python rather than python3 and if you have python2 on the machine, it might get confused.

James.

**Comment by Grant-Fox** [comment]
> 

Hello! I did not realize I was not using python3 during the `setup.py install` but I made this change and it did not fix my problem. I got the same error as previous.

**Comment by hiruna72** [comment]
Hello @Grant-Fox,

I have not used easy_install. But similar issues have been [reported](https://github.com/jmaupetit/md2pdf/issues/29) regarding easy_install. Easy_install is now[ deprecated](https://packaging.python.org/en/latest/discussions/pip-vs-easy-install/) as well.
I quite don't understand how easy_install takes control over installing packages when you follow the commands as listed in the Readme? My idea was it is using pip.

```
git clone https://github.com/hiruna72/squigualiser.git
cd squigualiser
python3.8 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools wheel

export PYSLOW5_ZSTD=1 # if your slow5 file uses zstd compression and you have zstd installed, set
python setup.py install
squigualiser --help
```

However, as an alternative could you please try the conda installation?
```
git clone https://github.com/hiruna72/squigualiser.git
cd squigualiser
conda create -n squig python=3.8.0 -y
conda activate squig

export PYSLOW5_ZSTD=1 # if your slow5 file uses zstd compression and you have zstd installed, set

python setup.py install
squigualiser --help
```

**Comment by Grant-Fox** [comment]
@hiruna72,

I am attempting to install conda on to my local computer. To create the virtual environment with the python=3.8.0 is giving me issues. I am getting PackagesNotFoundError when attempting to build the squig environment with conda.

**Comment by hiruna72** [comment]
Hello @Grant-Fox,

Really sorry for the late response.
Squigualiser is now available through pip.
Could you please try the following commands.
````
python3.8 -m venv venv3
source venv3/bin/activate
pip install --upgrade pip

pip install squigualiser

squigualiser --help
````

If it fails, could you try the following. 
@hasindu2008 handled the pysam installation to make this precompile binary. 
The caveat is this binary only works on common Linux distributions.
````
wget https://github.com/hiruna72/squigualiser/releases/download/v0.3.0/squigualiser-v0.3.0-linux-x86-64-binaries.tar.gz -O squigualiser.tar.gz
tar xf squigualiser.tar.gz
cd squigualiser
./squigualiser --help
````

The latest release is at https://github.com/hiruna72/squigualiser/releases/tag/v0.3.0

**Comment by hiruna72** [comment]
I will close this issue for now. Feel free to reopen if you face difficulties installing.
