### ISSUE TITLE
Squig pileup region error

### ISSUE THREAD

**Issue by katiestoker** [hiruna72/squigualiser#38]
Hello, 

I am attempting to generate a signal to reference pileup using the following command:

REF=../linear_amplicon.fasta
ALIGNMENT=02_MHhal_squig_align.bam
OUTPUT_DIR=02_pileup
REGION=pSHNJXXX_Linear_-_pOSIP:34-110

squigualiser plot_pileup -f ${REF} -s ../signals.blow5 -a ${ALIGNMENT} -o ${OUTPUT_DIR} --region ${REGION} --tag_name "pileup"

The pileup is successfully generated when I use any region between 1-30, however anything over 30 and I receive an error message (attached at the bottom) e.g. 1-31, 30-60 etc.

I receive the same error message when running the command on my other data set too...

![image](https://github.com/hiruna72/squigualiser/assets/98974037/8e38d9b0-4816-4d35-a5ed-c852886b0509)

Many thanks, 
Katie.

**Comment by hiruna72** [comment]
Hi @katiestoker,

Can you do a quick test separately by downloading the prebuilt executable (linux or macos) and running it on the given sample dataset?

The commands are available [here](https://github.com/hiruna72/squigualiser#quickstart)

Thank you!

**Comment by katiestoker** [comment]
Hello, 

I gave it a go and everything worked fine on the executable with the test data...
I tried running my own data here too but received a key error message again:

![image](https://github.com/hiruna72/squigualiser/assets/98974037/6a0a89ec-a210-4bf7-a7bc-1663f5127b42)

Thanks!

**Comment by hiruna72** [comment]
Hello,

Really sorry for the trouble. Can you please upload a minimal dataset with the commands you ran so that I can reproduce the error? It makes easy for me to debug.

Thank you.

**Comment by katiestoker** [comment]
Hello, 
Yes I have attached the files below...
BAM file:
[02_MHhal_squig_align.zip](https://github.com/hiruna72/squigualiser/files/12407902/02_MHhal_squig_align.zip)

Reference:
[linear_amplicon.zip](https://github.com/hiruna72/squigualiser/files/12407904/linear_amplicon.zip)

Blow5 subset:
https://drive.google.com/file/d/1mJnZWlJ1LW87LR98np6s72ESMgavfxj-/view?usp=sharing

The commands I ran are as follows:
REF=linear_amplicon.fasta 

MAP_SAM=mapped_02_MHhal.sam
[mapped_02_MHhaI.zip](https://github.com/hiruna72/squigualiser/files/12407983/mapped_02_MHhaI.zip)

FASTQ=02_MHhal_filtered.fastq
[02_MHhaI_filtered.zip](https://github.com/hiruna72/squigualiser/files/12407976/02_MHhaI_filtered.zip)

minimap2 -ax map-ont ${REF} ${FASTQ} -t8 --secondary=no -o ${MAP_SAM}

SIGNAL=signals.blow5 (the full dataset merged blow5 file)
f5c index ${FASTQ} --slow5 ${SIGNAL}

ALIGNMENT=02_MHhal_squig_align.bam
f5c eventalign -b mapped_02_MHhal.bam -r ${FASTQ} -g ${REF} --slow5 ${SIGNAL} -a -o 02_squig_eventalign.sam

samtools sort 02_squig_eventalign.sam -o ${ALIGNMENT}
samtools index ${ALIGNMENT}

squigualiser plot_pileup -f ${REF} -s ${SIGNAL_FILE} -a ${ALIGNMENT} -o ${OUTPUT_DIR} --region ${REGION} --tag_name "pileup"

Apologies for the long comment!

Thanks for the help.
Katie.

**Comment by hiruna72** [comment]
Hi Katie,

The issue is with the reference file I guess. It has both lower and upper case bases. When I replace all with upper case it worked for. Is there a valid reason to have a mix of cases?

**Comment by katiestoker** [comment]
Hello, 

After changing this it has worked!
I seem to have checked for this issue in the SAM file rather than the reference file...
This is a mistake in the formatting, no valid reason for mix of cases. 

Thanks for all your help.

All the best, 
Katie.

**Comment by katiestoker** [comment]
Great!

I will take a look at the pipeline scripts too!

Thanks again for the help! (:
