### ISSUE TITLE
plot_tracks doesn't exist

### ISSUE THREAD

**Issue by kaltinel** [hiruna72/squigualiser#39]
Hi,

I am trying to use the `plot_tracks` option and created a `command_file.txt` where I have 2 `plot_pileup` commands as instructed in your `README.md`.

However, I am unable to call `squigualiser plot_tracks --shared_x -f ${COMMAND_FILE} -o ${OUTPUT_DIR}` as I receive an error of 
```
usage: squigualiser [-h] [-v] {plot,reform,realign,plot_pileup} ...
squigualiser: error: argument command: invalid choice: 'plot_tracks' (choose from 'plot', 'reform', 'realign', 'plot_pileup')
```

Do I use a wrong version of the tool, perhaps, as I don't have this optional argument?

I would be glad to hear back from you, thank you.

**Comment by hiruna72** [comment]
Hello @kaltinel,

Yes, you are using an old version. Can you download the prebuilt binaries, run the test command for the sample dataset and then try your command?

The commands are available [here](https://github.com/hiruna72/squigualiser#quickstart)

**Comment by kaltinel** [comment]
Hi @hiruna72,

Thank you very much for your answer. I installed it from scratch and now all arguments are complete.
