### ISSUE TITLE
can not iterate over samfile without header

### ISSUE THREAD

**Issue by Flower9618** [hiruna72/squigualiser#4]
Hi, when I run `squigualiser reform --sig_move_offset 1 --kmer_length 1 -c --bam out.bam -o ${ALIGNMENT}`, there is an error:
`File "squigualiser-0.0.1-py3.8.egg/src/reform.py", line 39, in run
File "pysam/libcalignmentfile.pyx", line 1850, in pysam.libcalignmentfile.AlignmentFile.__iter__
NotImplementedError: can not iterate over samfile without header`

Because the .sam file is from dorado, it is without header, can anyone help me to solve this problem? 
Thank you very much!

**Comment by hiruna72** [comment]
Hi, 

yes a hack is explained [here](https://github.com/hiruna72/squigualiser#note) at Note 7.

**Comment by Flower9618** [comment]
Hi, @hiruna72,
Thank you so much for your patient explanation. I solved this problem.
When I run `squigualiser plot,` there is another error:
`  File "squigualiser-0.0.1-py3.8.egg/src/plot.py", line 384, in run               
TypeError: 'NoneType' object is not iterable`

**Comment by hiruna72** [comment]
Hi @Flower9618,

Did you create a paf file from the dorado sam output? You actually pass the reformed.paf file along with the slow5 file to plot function, not the sam file. 
This is the step 2 in [option 1](https://github.com/hiruna72/squigualiser#option-1---using-move-table-generated-by-the-basecaller)

**Comment by Flower9618** [comment]
![image](https://user-images.githubusercontent.com/77596901/229761190-1442c3fc-0227-4a82-a35c-77fe32749c27.png)
This is my workflow.

**Comment by Flower9618** [comment]
Hi, @hiruna72 ,
I know the reason. `--alignment` should be .paf file. I solved the problem and plot the signal successfully.
Thank you so much.

**Comment by hiruna72** [comment]
Thanks @Flower9618, I know it is a bit of work. I will write a bash script to compile all the commands together. I will do this when the tools is more stable. Also I will burrow your figure. It is very useful for new users. I will add it to the Readme.
