### ISSUE TITLE
tag mv not found

### ISSUE THREAD

**Issue by UmairK291095** [hiruna72/squigualiser#41]
raise Exception("Error: tag '{}' is not found. Please check your input SAM/BAM file.".format("mv"))
Exception: Error: tag 'mv' is not found. Please check your input SAM/BAM file

this error is showing while runnign this code "# PAF output for plotting
ALIGNMENT=reform_output.paf
squigualiser reform --sig_move_offset 0 --kmer_length 1 -c --bam out.sam -o ${ALIGNMENT}"

**Comment by hasindu2008** [comment]
What's the command you used for basecalling? Likely you missed the flag to ensure to move table.

**Comment by UmairK291095** [comment]
dorado basecaller dna_r10.4.1_e8.2_400bps_sup@v4.2.0 /data/gecko/bioinf_shared/minion_storage/230615-FNB-mk1c/KLPN/20230615_1225_MC-115296_FAW84557_c4d119ad/pod5 > /home/user_pool_1/mohd/POD5/230615-FNB/calls.bam

**Comment by hiruna72** [comment]
Hi @UmairK291095,

Please pass the argument `--emit-moves`.

**Comment by UmairK291095** [comment]
Worked. Thanks
