### ISSUE TITLE
squigualiser realign gives only multiples of stride(=5) in the original model

### ISSUE THREAD

**Issue by Marjan-Hosseini** [hiruna72/squigualiser#44]
I am trying to use squigualiser realign to re-squiggle the move table generated by Dorado, using the following command:
```
squigualiser realign -p reform_output.paf -b sorted_t2t.bam -c -o realigned.paf
```
It gives me a move table similar to:
![image](https://github.com/hiruna72/squigualiser/assets/45966768/b8967101-4fe8-4933-8a39-7280428f7efe)

The problem is that moves seems to be all multiples of 5. Is there a way I can get a move table values that are not multiples of 5?

**Comment by hasindu2008** [comment]
Move tables from Guppy or Dorado are always a multiple of a stride size. 
You can use the f5c eventalign method which provides alignments that are not multiples of any number.

**Comment by hiruna72** [comment]
@Marjan-Hosseini squigualiser's realign tool does not refine boundaries. Please use f5c eventalign.
Also have a look at these documents. 
https://github.com/hiruna72/squigualiser/blob/main/docs/different_alignments.md
https://github.com/hiruna72/squigualiser/blob/main/docs/RNA_visualisation.md

**Comment by hiruna72** [comment]
Hello @Marjan-Hosseini,

I will close this issue now. Feel free to open again if you face related problems.
