### ISSUE TITLE
Stride length unit

### ISSUE THREAD

**Issue by lkwhite** [hiruna72/squigualiser#47]
Hi Hiruna,

This looks like a really great tool, and I wanted to thank you for your detailed documentation of distinction between generating nucleotide-anchored signal with f5c and what you get from the move table.

Since [this is the most detailed explanation of the move table](https://github.com/hiruna72/squigualiser/blob/main/docs/move_table.md) I've seen anywhere, I was hoping you could answer a quick question: when we say that the DNA stride length is 5 and the RNA stride length is 10, am I correct in understanding that those values are the **number of sampling events** the basecalling neural network lumps together to downsample the signal data?

**Comment by hiruna72** [comment]
Hello @lkwhite,

Yes you are correct. 

As of [dorado_v0.4.0](https://github.com/nanoporetech/dorado/tree/v0.4.0) stride is used in three stages.
1. In the process of creating chunks to feed into the NN model ([code](https://github.com/nanoporetech/dorado/blob/b2af8e828a03d85448bb39ee5629660e6ef5e74f/dorado/read_pipeline/BasecallerNode.cpp#L78)).
2. NN calculations on GPU (have a look at `stride` in the `config.toml` file inside a model directory).
3. To properly stitch the output of each chunk to generate the final fastq sequence ([code](https://github.com/nanoporetech/dorado/blob/b2af8e828a03d85448bb39ee5629660e6ef5e74f/dorado/read_pipeline/stitch.cpp#L12)). This confirms that the NN model is down sampling the raw signal.


@vellamike could you please confirm the above details? Thank you.

**Comment by lkwhite** [comment]
Thanks, that's super helpful!
