### ISSUE TITLE
Base-Wise alginment question

### ISSUE THREAD

**Issue by xianyu0623** [hiruna72/squigualiser#59]
Hi hiruna72! 
Thank you for proposing such a fantastic tool for nanopore raw data. I have some questions on how the tool implements base-wise alignment. I have read some papers about the raw data alignment, but they focus on kmer-event alignment. If I do not make it wrong, for a Kmer-event alignment pair, you align the event's signal to the middle base in a Kmer. Is it right?
Thanks a lot for your help!

**Comment by hiruna72** [comment]
Hi @xianyu0623,

Thanks for appreciating our work.
 
Yes, you are correct, we transform the kmer-to-signal alignment to a (most significant/influential) middle base-to-signal alignment.

You can find the middle base indices we have figured for different nanopore chemistry, pore model and base calling models.
https://github.com/hiruna72/squigualiser/blob/main/docs/profiles.md#precomputed-forward-and-reverse-base-shift-values

For more details refer to your preprint (specially the sup note 3).
https://www.biorxiv.org/content/10.1101/2024.02.19.581111v2

**Comment by xianyu0623** [comment]
Thanks a lot for your timely answer!
