### ISSUE TITLE
Plot Signal-to-Read Alignment for Multiple Reads from a List

### ISSUE THREAD

**Issue by denisbeslic** [hiruna72/squigualiser#65]
Hi,

I'm currently working on visualizing signal-to-read alignments using the basecaller move-table from dorado. In the final step (plot signal-to-read alignment), I need to plot only a specific subset of reads rather than all of them.

I've tried using the `-r READ_ID` option, but it only accepts a single Read ID at a time. Is there a way to specify a list of Read IDs from a file (e.g., in .txt format) or another format to filter the reads for plotting?

Thank you for your help!

**Comment by hiruna72** [comment]
Hey,

Have you tried `--read_list` argument? It takes a .txt file.
`-l, --read_list STR` (optional) Path to a file containing a list of read_ids to plot only the reads listed.

**Comment by denisbeslic** [comment]
Ah, I missed that. Perfect, thanks!
